manifests/kustomization.yaml, manifests/mosquitto/deployment.yaml, manifests/mosquitto/kustomization.yaml, manifests/mosquitto/mosquitto.conf, manifests/mosquitto/service_account.yaml, manifests/mosquitto/services.yaml, manifests/telegraf/deployment.yaml, manifests/telegraf/kustomization.yaml, manifests/telegraf/telegraf.conf
=> add mosquitto

manifests/README.md, manifests/influxdb2-values.yaml
finalized implementation of #3 
=> add influxdb to the manifests

docker-compose/grafana/provisioning/datasources/influxdb.yml, docker-compose/telegraf/telegraf.conf
- Updated telegrf.conf to support UserID, SessionID, GameName, TrackCode, CarModel, SessionType
- Fixed Grafana not connecting to InfluxDB
=> Updated Docker to current standard

manifests/telegraf/kustomization.yaml, manifests/telegraf/telegraf.toml
=> telegraf: renamed and reconfigured to use TOML

manifests/mosquitto/deployment.yaml, manifests/mosquitto/kustomization.yaml, manifests/mosquitto/mosquitto.conf, manifests/mosquitto/mosquitto.conf.old, manifests/mosquitto/passwd, manifests/mosquitto/service_account.yaml, manifests/mosquitto/services.yaml, manifests/telegraf/deployment.yaml, manifests/telegraf/kustomization.yaml, manifests/telegraf/service.yaml, manifests/telegraf/service_account.yaml, manifests/telegraf/telegraf.conf
- updated mosquitto and telegraf manifests
=> updated mosquitto and telegraf manifests

manifests/kustomization.yaml
=> fix commonLabels

manifests/postgresql/overlays/smaug/secret-generator.yaml, manifests/telegraf/overlays/smaug/secret-generator.yaml
=> fix secret-generator names

manifests/keycloak/base/deployment_config.yaml, manifests/postgresql/base/pgbouncer.yaml
=> refine resource to be used by deployments

.github/ISSUE_TEMPLATE/1_request_pitcrew.yaml, scripts/jsonnet/pitcrew.jsonnet, scripts/pitcrew_new.sh
issue template
onboarding script
=> onboarding automation

components/paddock/Pipfile, components/paddock/Pipfile.lock, components/paddock/paddock/settings.py, components/paddock/telemetry/admin.py, components/paddock/telemetry/management/commands/analyze.py, components/paddock/telemetry/management/commands/pitcrew.py, components/paddock/telemetry/models.py, components/paddock/telemetry/pitcrew/coach.py, components/paddock/telemetry/pitcrew/crew.py, components/paddock/telemetry/pitcrew/history.py, components/paddock/telemetry/pitcrew/mqtt.py, manifests/paddock/overlays/smaug/image_stream_tag.yaml
- pitcrew in paddock
- bump paddock
=> pitcrew paddock

manifests/telegraf/overlays/smaug/telegraf.conf
settings for the next iteration of crewchief
=> v2 telegraf

manifests/telegraf/overlays/smaug/telegraf.conf
=> telegraf time

components/paddock/telemetry/pitcrew/crew.py
=> quick fix timing

components/paddock/telemetry/fast_lap_analyzer.py, components/paddock/telemetry/management/commands/analyze.py, components/paddock/telemetry/management/commands/pitcrew.py, components/paddock/telemetry/pitcrew/coach.py, components/paddock/telemetry/pitcrew/crew.py, components/paddock/telemetry/pitcrew/history.py
=> analyzer and coach

components/paddock/telemetry/pitcrew/crew.py, components/paddock/telemetry/pitcrew/history.py
=> fix lap saving

components/paddock/telemetry/pitcrew/crew.py
=> lap / session cleaning

components/paddock/telemetry/pitcrew/history.py
=> less logging

manifests/grafana/overlays/smaug/dashboards/details-crew-chief.json, manifests/grafana/overlays/smaug/dashboards/landingpage.json
=> fix grafana dashboards

manifests/influxdb2-values.yaml
=> increase the PCV size for influxdb2

components/paddock/telemetry/management/commands/pitcrew.py, components/paddock/telemetry/management/commands/replay.py, components/paddock/telemetry/pitcrew/coach.py, components/paddock/telemetry/pitcrew/coach_watcher.py, components/paddock/telemetry/pitcrew/crew.py, components/paddock/telemetry/pitcrew/session.py, components/paddock/telemetry/pitcrew/session_saver.py
- healthz for crew
- watch coaches
=> watch coaches

manifests/paddock/base/job_copy_influx.yaml, manifests/paddock/overlays/smaug/image_stream_tag.yaml
=> switch to ghcr registry

.github/workflows/pull_request.yaml, .github/workflows/push_to_main.yaml, .github/workflows/tag_release.yaml, components/paddock/Containerfile
see [S2I doc](https://github.com/sclorg/s2i-python-container/tree/master/3.10)
=> migrate to s2i base image

.github/workflows/pull_request.yaml
🔏 do not push a container image on each PR, just build it
=> no image push on pr

components/paddock/telemetry/pitcrew/coach_watcher.py, components/paddock/telemetry/pitcrew/crew.py, components/paddock/telemetry/pitcrew/mqtt.py, components/paddock/telemetry/pitcrew/session_saver.py, manifests/base/paddock/paddock-settings.yaml
and check if threads are ready
=> get mqtt host from env

components/paddock/telemetry/influx.py, components/paddock/telemetry/management/commands/replay.py
- better influx connection handling
=> replay mqtt better influx connection handling

components/paddock/telemetry/analyzer.py, components/paddock/telemetry/fast_lap_analyzer.py, components/paddock/telemetry/management/commands/analyze.py, manifests/base/postgresql/cluster.yaml
- edge case: lap with full throttle
- psql repo retention
=> edge case: lap with full throttle

components/paddock/README.md, components/paddock/telemetry/pitcrew/coach.py, components/paddock/telemetry/pitcrew/history.py
- fix logging
- better debugging messages
=> better debugging messages

.github/workflows/pull_request.yaml, manifests/base/grafana-v5/datasource-influx.yaml, manifests/base/influxdb/README.md, manifests/base/influxdb/init.yaml, manifests/base/paddock/cronjobs/cronjob_analyze.yaml, manifests/base/paddock/cronjobs/kustomization.yaml, manifests/base/paddock/kustomization.yaml, manifests/base/paddock/paddock-ingress.yaml, manifests/base/paddock/paddock-settings.yaml, manifests/base/postgresql/cluster.yaml, manifests/base/telegraf/deployment.yaml, manifests/base/telegraf/telegraf.conf, manifests/env/phobos.test/README.md, manifests/env/phobos.test/kustomization.yaml, manifests/env/phobos.test/namespace.yaml, manifests/env/phobos/kustomization.yaml
- ingress follow up
- phobos test
=> ingress.test

components/paddock/telemetry/analyzer.py
=> recursion fix duh

components/paddock/telemetry/analyzer.py, components/paddock/telemetry/pitcrew/history.py, components/paddock/telemetry/pitcrew/message.py
- edge case in resample
- fine tune read time
=> edge case in resampling / fine tune read time

.prow.yaml, .tekton/push.yaml, .tekton/tasks/e2e-telemetry-test.yaml, components/paddock/README.md, components/paddock/e2e-test.sh, components/paddock/paddock/settings.py
=> ✨ add telemetry e2e test

manifests/README.md
=> 📝 describe how to use sops-encrypted file to recreate sealed secrets

components/paddock/paddock/fastlap_app.py
- fix migrations
fixes #308 
cc @goern
=> fix migrate

components/paddock/Pipfile, components/paddock/Pipfile.lock, components/paddock/paddock/settings.py, components/paddock/paddock/urls.py, components/paddock/telemetry/models.py, manifests/base/paddock/deployment_config.yaml, manifests/base/paddock/kustomization.yaml, manifests/base/paddock/paddock-settings.yaml
=> ✨ 🌡️ add prometheus metrics exporter basics

components/paddock/README.md, components/paddock/paddock/settings.py
=> 🖹 update the readme: how to use a local postgresql

manifests/base/paddock/deployment_config.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> add some defaults, so that argocd sync view is more in sync

manifests/env/phobos/postgresql/kustomization.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> some changes applied on prod, now in git

README.md, components/paddock/telemetry/pitcrew/session.py, docs/backup.md, manifests/base/telegraf/telegraf.conf, manifests/env/phobos/kustomization.yaml, manifests/env/phobos/telegraf/kustomization.yaml, scripts/psql.sh, scripts/publish.sh, scripts/sample.json, scripts/setup_secrets.sh, scripts/subscribe.sh
- add CarClass as tag to telegraf
- small scripts adjustments
- backup docs
- catch telemetry not being a dict
=> misc stuff

components/paddock/telemetry/pitcrew/coach.py, components/paddock/telemetry/tests/data/responses_test_coach.txt
- adjust timing of sending responses
=> adjust timing of sending responses

manifests/base/grafana-v5/dashboards/kustomization.yaml, manifests/base/grafana-v5/dashboards/landingpage-extended.json
- add dashboard extended
- change landingpage ext uid
=> add dashboard extended

manifests/base/grafana-v5/dashboards/details-extended.json, manifests/base/grafana-v5/dashboards/landingpage-extended.json, manifests/base/grafana-v5/dashboards/landingpage.json
=> tweak dashboard names

manifests/base/grafana-v5/dashboards/details-crew-chief.yaml, manifests/base/grafana-v5/dashboards/landingpage-extended.yaml, manifests/base/grafana-v5/dashboards/landingpage.yaml
=> resync period

manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
btw, this happens if you blindly trust GH copilot :/
=> fix session URL

manifests/env/nostromo-stage/namespace.yaml, manifests/env/phobos.dev/namespace.yaml, manifests/env/phobos.test/namespace.yaml, manifests/env/phobos/namespace.yaml
- user workload monitoring requied no label being present
=> fix user workload monitoring

components/paddock/kpi/views.py, components/paddock/paddock/metrics.py, components/paddock/paddock/urls.py, components/paddock/paddock/views.py
=> ✨ add a few application-lelvel key metrics

manifests/env/phobos/postgresql/kustomization.yaml
- fix gear if gear is NaN
- bump psql pvc
=> bump psql pvc

components/paddock/Pipfile, components/paddock/Pipfile.lock, components/paddock/paddock/settings.py, manifests/base/paddock/deployment_config.yaml, manifests/env/nostromo-stage/paddock/kustomization.yaml, manifests/env/nostromo-stage/postgresql/kustomization.yaml, manifests/env/phobos/grafana/kustomization.yaml, manifests/env/phobos/kustomization.yaml, manifests/env/phobos/paddock/kustomization.yaml, manifests/env/phobos/telegraf/kustomization.yaml
- put the prometheus metrics dir on an emptyDir
- add gunicorn and the allauth middleware
- just some cleanup of manifest files
=> env:phobos manifest cleanup

manifests/env/nostromo-stage/postgresql/alerting.yaml, manifests/env/nostromo-stage/postgresql/kustomization.yaml, manifests/env/phobos/postgresql/alerting.yaml, manifests/env/phobos/postgresql/kustomization.yaml
=> feat: add alerting for pgsql diff backup cronjob execution and pvc usage

components/paddock/telemetry/analyzer.py
=> fix interpolation range

.gitignore, components/paddock/k6.d/README.md, components/paddock/k6.d/average-load.js, components/paddock/k6.d/browser.js, components/paddock/k6.d/e2e.js, components/paddock/k6.d/smoke.js
=> test(paddock-tests): add a few k6-based test scripts

components/paddock/paddock/views.py
=> include fast lap app

components/paddock/Pipfile, components/paddock/Pipfile.lock
=> build: add sops2sealedsecret to dev packages

manifests/env/nostromo-stage/kustomization.yaml
=> build: update mosquitto and telegraf to their latest version

components/paddock/Pipfile, components/paddock/Pipfile.lock, components/paddock/paddock/__init__.py, components/paddock/pyproject.toml, manifests/base/paddock/deployment_config.yaml
- ➗ refactor(paddock): refined the resources of the deployment
- 🧼 correction(commitizen): remove commitizen from the dev environment
- 🎉 feat: paddock is reading its version string from pyproject.toml now
=> read version from pyproject toml

components/paddock/Pipfile.lock, manifests/base/grafana-v5/ingress.yaml, manifests/base/influxdb/ingress.yaml, manifests/base/paddock/ingress.yaml
- 🧼 correction(commitizen): remove commitizen from the dev environment
- fix: add ingressClassName where it was missing before
=> add ingressclass

manifests/env/phobos/influxdb/kustomization.yaml
=> bump_influx_storage

components/paddock/Pipfile, components/paddock/Pipfile.lock, components/paddock/telemetry/management/commands/load_data.py, notebooks/track_sections_from_coordinates.ipynb, scripts/publish_response.sh
=> add openai tts

components/paddock/api/telemetry_loader.py, components/paddock/api/templates/session.html, components/paddock/api/views.py, components/paddock/paddock/assets/session.css, components/paddock/paddock/assets/session.js, components/paddock/telemetry/influx.py
- Fix session view and add speed value
- Update telemetry display and remove distance slider
- Update telemetry_loader and views configurations
- Update telemetry caching and add event listeners for graph interactions
- Add lap selectors and update lap telemetry display
=> comparison lap

components/paddock/api/telemetry_loader.py, components/paddock/api/views.py, components/paddock/paddock/assets/session.js
- Refactor map highlighting and speed calculation in session.js
- Refactor session.js to improve relayout functionality
- Update map layout in session.js
- Update telemetry_loader.py, views.py, and session.js
=> session js

components/paddock/api/telemetry_loader.py, components/paddock/api/urls.py, components/paddock/api/views.py, components/paddock/paddock/assets/session.js, components/paddock/paddock/templates/session.html, components/paddock/paddock/urls.py, components/paddock/paddock/views.py
- Fix lap number parsing and set selected lap in lapSelector1
- compare laps
=> compare laps

components/paddock/api/telemetry_loader.py, components/paddock/paddock/assets/session.js, components/paddock/paddock/templates/session.html, components/paddock/paddock/views.py, components/paddock/telemetry/analyzer.py
- Fix handling of empty dataframes in TelemetryLoader and session.js
- Add additional telemetry graphs to session.html and telemetry_loader.py
- Refactor code to use forEach loop for hiding traces in speed and throttle graphs
- Add new columns to telemetry loader and disable zoom in session.js
- Add time graph to session.js
=> session view shows more data

components/paddock/paddock/settings.py, components/paddock/telemetry/management/commands/analyze.py, components/paddock/telemetry/management/commands/maintenance.py
- Add ThreadingIntegration to Sentry integrations
- Fix fastlaps by deleting fastlaps with no associated laps
- Handle exception in analyze_fast_laps
=> mixed fixes

components/paddock/api/telemetry_loader.py, components/paddock/b4mad_racing_website/templates/profile/details.html, components/paddock/b4mad_racing_website/templates/sessions/cards.html, components/paddock/frontpage/views.py, components/paddock/paddock/assets/session.js, components/paddock/paddock/templates/session.html, components/paddock/paddock/templates/sessions.html, components/paddock/paddock/views.py, components/paddock/telemetry/influx.py, components/paddock/telemetry/racing_stats.py, components/paddock/templates/site/home.html
- Refactor session display and add session cards
- Refactor session filtering and eager loading
- Add drop_tags parameter to telemetry_loader.py and fields parameter to influx.py
- Add track and car information to session view
- Refactor telemetry loading and lap comparison logic
- Update Plotly graph display options
- Add session details to sessions.html and optimize sessions view
=> session display on main page

manifests/base/mosquitto/deployment.yaml, manifests/base/mosquitto/mosquitto.conf, manifests/base/mosquitto/services.yaml, manifests/env/phobos/kustomization.yaml, manifests/env/phobos/mosquitto/kustomization.yaml, scripts/publish_response.sh, scripts/subscribe.sh
=> mosquitto also use TLS

manifests/base/paddock/deployment.yaml, manifests/base/postgresql/README.md, manifests/base/postgresql/cluster.yaml
- copy dc to deployment
- Update PostgreSQL image and fix uid issue
=> bump crunchy container version

components/paddock/templates/site/base.html, manifests/base/paddock/deployment.yaml
- fix trigger
- Hide newsletter subscription form
=> fix trigger / hide newslette

components/paddock/b4mad_racing_website/forms.py, manifests/base/paddock/deployment.yaml
- Commented out two form fields in ProfileForm
- Remove unused image stream tag definition
=> Commented out two form fields in ProfileForm
